spring.application.name=springmvc

spring.messages.basename=messages

logging.level.org.apache.coyote.http11=debug

#파일 하나의 사이즈
spring.servlet.multipart.max-file-size=1MB

#멀티파트 요청 하나에 여러 파일을 업로드 할 수 있는데, 그 전체의 합
spring.servlet.multipart.max-request-size=10MB

#서블릿 컨테이너는 멀티파트와 관련된 기능을 하지 않음
#기본 값 true
#spring.servlet.multipart.enabled=false

file.dir=D:/file/